# Generated by Django 4.1 on 2023-04-18 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('outline', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('outline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', 'COMMIT'), ('B', 'ISSUE'), ('C', 'PR')], max_length=2)),
                ('remote_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'COMPLETED'), ('B', 'INPROGRESS'), ('C', 'NOTSTART'), ('D', 'ILLEGAL')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('outline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=255)),
                ('remote_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('outline', models.TextField()),
                ('status', models.CharField(choices=[('A', 'COMPLETED'), ('B', 'INPROGRESS'), ('C', 'NOTSTART')], max_length=2)),
                ('contribute_level', models.IntegerField()),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.task')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'NORMAL'), ('B', 'ILLEGAL'), ('C', 'ADMIN')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'NORMAL'), ('B', 'ADMIN')], max_length=2)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'NORMAL'), ('B', 'ADMIN')], max_length=2)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user'),
        ),
        migrations.CreateModel(
            name='ProgressTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.progress')),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='repo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('content', models.TextField()),
                ('belongingTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'TEXT'), ('B', 'PIC'), ('C', 'FILE')], max_length=2)),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user'),
        ),
    ]
