# Generated by Django 4.1 on 2023-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('A', 'NORMAL'), ('B', 'ADMIN'), ('C', 'DEVELOPER')], max_length=3),
        ),
    ]
