# Generated by Django 3.2.14 on 2023-03-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_createtime', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=64)),
                ('customer_address', models.CharField(max_length=64)),
                ('customer_mobile', models.CharField(max_length=64)),
                ('customer_province', models.CharField(max_length=16, null=True)),
                ('customer_city', models.CharField(max_length=16, null=True)),
                ('customer_area', models.CharField(max_length=16, null=True)),
                ('business_name', models.CharField(max_length=64)),
                ('business_address', models.CharField(max_length=64)),
                ('business_mobile', models.CharField(max_length=64)),
                ('business_province', models.CharField(max_length=16, null=True)),
                ('business_city', models.CharField(max_length=16, null=True)),
                ('business_area', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_sales', models.IntegerField()),
                ('product_color', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='avatar/')),
                ('product_imageDetail', models.ImageField(upload_to='avatar/')),
                ('product_stock', models.IntegerField(null=True)),
                ('product_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('user_password', models.CharField(max_length=64)),
                ('user_type', models.CharField(max_length=10, null=True)),
                ('user_address', models.CharField(max_length=64, null=True)),
                ('user_mobile', models.CharField(max_length=64, null=True)),
                ('user_avatar', models.ImageField(default='user_avatar/default_avatar.jpg', null=True, upload_to='user_avatar/')),
                ('user_createtime', models.DateField(auto_now_add=True, null=True)),
                ('user_province', models.CharField(max_length=16, null=True)),
                ('user_city', models.CharField(max_length=16, null=True)),
                ('user_area', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('log_name', models.CharField(max_length=16)),
                ('log_type', models.CharField(max_length=10, null=True)),
                ('log_province', models.CharField(max_length=16, null=True)),
                ('log_city', models.CharField(max_length=16, null=True)),
                ('log_area', models.CharField(max_length=16, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_name', models.CharField(max_length=16)),
                ('action_type', models.CharField(max_length=10)),
                ('action_province', models.CharField(max_length=16, null=True)),
                ('action_city', models.CharField(max_length=16, null=True)),
                ('action_area', models.CharField(max_length=16, null=True)),
                ('action', models.CharField(max_length=16)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.IntegerField()),
                ('stock_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock_createtime', models.DateTimeField(auto_now_add=True)),
                ('business_province', models.CharField(max_length=16, null=True)),
                ('business_city', models.CharField(max_length=16, null=True)),
                ('business_area', models.CharField(max_length=16, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='StarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_business', to='myApp.userinfo')),
                ('star_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_customer', to='myApp.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo'),
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('order_product_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.orderinfo')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='myApp.userinfo'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='myApp.userinfo'),
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_createtime', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_image1', models.ImageField(upload_to='comments/')),
                ('comment_image2', models.ImageField(upload_to='comments/')),
                ('comment_image3', models.ImageField(upload_to='comments/')),
                ('comment_value', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CheckProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_color', models.CharField(max_length=20)),
                ('product_image', models.ImageField(default='avatar/default_pic.jpg', upload_to='avatar/')),
                ('product_imageDetail', models.ImageField(default='avatar/default_pic.jpg', upload_to='avatar/')),
                ('checktime', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.CharField(max_length=10)),
                ('check_status', models.CharField(max_length=10)),
                ('product_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.userinfo')),
            ],
        ),
    ]
