# Generated by Django 3.2.14 on 2023-03-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20230324_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='checkproduct',
            name='product_business',
        ),
        migrations.RemoveField(
            model_name='checkproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='likelist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_business',
        ),
        migrations.RemoveField(
            model_name='starlist',
            name='star_business_id',
        ),
        migrations.RemoveField(
            model_name='starlist',
            name='star_customer_id',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='action_id',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
        migrations.DeleteModel(
            name='CheckProduct',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LikeList',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StarList',
        ),
        migrations.DeleteModel(
            name='StockInfo',
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
