# Generated by Django 4.1 on 2023-04-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contribute_level',
            field=models.IntegerField(default=0),
        ),
    ]
